version: "3.7"

services:
  postgres:
    image: postgres:latest
    init: true
    restart: always

    env_file:
      - .env

    expose:
      - 5432

    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${POSTGRES_STORAGE_DIR}:/var/lib/postgresql/data/:rw

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  holiday-hackathon-bot:
    image: docker.pkg.github.com/foothillcsclub/holiday-hackathon-bot/holiday-hackathon-bot:latest
    container_name: holiday-hackathon-bot
    init: true
    restart: always

    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - .env
