version: "3.7"

services:

  postgres:
    image: postgres:latest
    init: true
    restart: always

    env_file:
      - .env

    expose:
      - 5432

    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./postgres_data/:/var/lib/postgresql/data/

  holiday-hackathon-bot:
    container_name: holiday-hackathon-bot
    init: true
    restart: always

    depends_on:
      - postgres

    env_file:
      - .env

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      # - ./logs:/holiday-hackathon-bot/logs:rw
      - .:/holiday-hackathon-bot:ro

    ports:
      - "5005:5000"
