name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: docker.pkg.github.com/foothillcsclub/holiday-hackathon-bot/holiday-hackathon-bot

    steps:
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.IMAGE_NAME }}
          tag-sha: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Login to GitHub Packages Registry
        uses: docker/login-action@v1 
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            ${{ github.ref == 'refs/heads/main' && format('{0}:latest', env.IMAGE_NAME) || '' }}
          labels: ${{ steps.docker_meta.outputs.labels }}
