name: Linting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Lint with black
        uses: psf/black@stable

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev --deploy --system

      - name: Lint with flake8
        run: |
          flake8 ./
